# -*- coding: utf-8 -*-
"""walmart_data_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XM2lObsu3sXy3aYbvsU0iNZxsGR0znnw
"""

import pandas as pd

data = pd.read_csv("Walmart_Sales.csv")
print("Structured Data Sample:")
print(data.head())

json_data = pd.read_json("/content/sample_data/anscombe.json")
print("Semi-Structured Data Sample:")
print(json_data.head())

